language: node_js
node_js:
    - "4"
    - "5"
    - "6"

addons:
    code_climate:
        repo_token: 9917845c93f86311acdafbe9e52ff4006836b4f98059000c5df6352f7c21c5f7

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info